-- Migration 028: Subcontractor directory
-- Separate from public.subcontractors (migration 024), which is the Job
-- Schedule's crew list and is readable by all users. This table holds the
-- full contact directory and is admin-only.
-- Mirrors the fields in the cleaned subcontractors.json. Phone, email and
-- website are arrays because some contractors have more than one.
-- Rows 1–115 are the imported list (seeded with their original ids); rows
-- added later get ids starting at 1000 so they never collide with the import.

CREATE TABLE IF NOT EXISTS public.subcontractor_directory (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  service     TEXT NOT NULL,     -- trade category, e.g. 'Plumbing', 'Framing/Drywall'
  name        TEXT,              -- contact person
  company     TEXT,
  specialty   TEXT NOT NULL,     -- searchable trade description
  phone       TEXT[] NOT NULL DEFAULT '{}',
  email       TEXT[] NOT NULL DEFAULT '{}',
  website     TEXT[] NOT NULL DEFAULT '{}',
  address     TEXT,
  license     TEXT,
  reference   TEXT,              -- how we know them / who referred them
  notes       TEXT
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'subcontractor_directory_updated_at'
  ) THEN
    CREATE TRIGGER subcontractor_directory_updated_at
      BEFORE UPDATE ON public.subcontractor_directory
      FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS subcontractor_directory_service_idx ON public.subcontractor_directory (lower(service));

-- RLS: contact details are confidential — admins only.
-- (Server-side code using the service role key bypasses RLS.)
ALTER TABLE public.subcontractor_directory ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage subcontractor directory" ON public.subcontractor_directory;
CREATE POLICY "Admins manage subcontractor directory"
  ON public.subcontractor_directory
  FOR ALL
  USING  (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

NOTIFY pgrst, 'reload schema';
