-- Migration 028: Subcontractors directory
-- Mirrors the fields in the cleaned subcontractors.json. Phone, email and
-- website are arrays because some contractors have more than one.
-- Rows 1–115 are the imported list (seeded with their original ids); rows
-- added later get ids starting at 1000 so they never collide with the import.

CREATE TABLE IF NOT EXISTS public.subcontractors (
  id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1000),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  service     TEXT NOT NULL,     -- trade category, e.g. 'Plumbing', 'Framing/Drywall'
  name        TEXT,              -- contact person
  company     TEXT,
  specialty   TEXT NOT NULL,     -- searchable trade description
  phone       TEXT[] NOT NULL DEFAULT '{}',
  email       TEXT[] NOT NULL DEFAULT '{}',
  website     TEXT[] NOT NULL DEFAULT '{}',
  address     TEXT,
  license     TEXT,
  reference   TEXT,              -- how we know them / who referred them
  notes       TEXT
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'subcontractors_updated_at'
  ) THEN
    CREATE TRIGGER subcontractors_updated_at
      BEFORE UPDATE ON public.subcontractors
      FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS subcontractors_service_idx ON public.subcontractors (lower(service));

-- RLS: contact details are confidential — admins only.
-- (Server-side code using the service role key bypasses RLS.)
ALTER TABLE public.subcontractors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage subcontractors" ON public.subcontractors;
CREATE POLICY "Admins manage subcontractors"
  ON public.subcontractors
  FOR ALL
  USING  (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

NOTIFY pgrst, 'reload schema';
